paths:
  /stores:
    post:
      tags:
        - Store
      summary: 특정 지역에 가게 추가하기
      parameters:
        - name: createStore
          in: body
          required: true
          schema:
            $ref: '#/definitions/CreateStoreRequest'
      responses:
        '201':
          description: 가게 등록 성공!
          schema:
            $ref: '#/definitions/CreateStoreResponse'
        '400':
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/ParameterNotFoundError'
        '500':
          description: 서버 에러
          schema:
            $ref: '#/definitions/BaseError'
  /stores/{store-id}/reviews:
    post:
      tags:
        - Store
      summary: 특정 가게에 리뷰 추가하기
      parameters:
        - name: store-id
          in: path
          required: true
          type: integer
          description: 가게 ID
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/AddReviewRequest'
      responses:
        '201':
          description: '리뷰 등록 성공!'
          schema:
            $ref: '#/definitions/StoreReviewResponse'
        '400':
          description: '잘못된 요청'
          schema:
            $ref: '#/definitions/ParameterNotFoundError'
        '404':
          description: '가게 정보가 존재하지 않음'
          schema:
            $ref: '#/definitions/StoreNotFoundError'
        '500':
          description: '서버 에러'
          schema:
            $ref: '#/definitions/BaseError'
    get:
      tags:
        - Store
      summary: 특정 가게의 리뷰 목록 조회
      parameters:
        - name: store-id
          in: path
          required: true
          type: integer
          description: 가게 ID
        - name: reviewId
          in: query
          required: false
          type: integer
          description: 기준 리뷰 ID (커서)
        - name: size
          in: query
          required: false
          type: integer
          description: 조회할 리뷰 개수
      responses:
        '200':
          description: 리뷰 목록 조회 성공
          schema:
            $ref: '#/definitions/StoreReviewsResponse'
        '400':
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/ParameterNotFoundError'
        '404':
          description: 가게 정보가 존재하지 않음
          schema:
            $ref: '#/definitions/StoreNotFoundError'
        '500':
          description: 서버 에러
          schema:
            $ref: '#/definitions/BaseError'
  /stores/{store-id}/missions:
    post:
      tags:
        - Store
      summary: 특정 가게에 미션 추가하기
      parameters:
        - name: store-id
          in: path
          required: true
          type: integer
          description: 가게 ID
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/AddStoreMissionRequest'
      responses:
        '200':
          description: 미션 추가 성공
          schema:
            $ref: '#/definitions/StoreMissionResponse'
        '400':
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/ParameterNotFoundError'
        '404':
          description: 가게 정보가 존재하지 않음
          schema:
            $ref: '#/definitions/StoreNotFoundError'
        '500':
          description: 서버 에러
          schema:
            $ref: '#/definitions/BaseError'
    get:
      tags:
        - Store
      summary: 특정 가게의 미션 목록 조회
      parameters:
        - name: store-id
          in: path
          required: true
          type: integer
          description: 가게 ID
        - name: page
          in: query
          required: false
          type: integer
          description: 요청 페이지 (1이상)
        - name: size
          in: query
          required: false
          type: integer
          description: 조회할 미션 개수
      responses:
        '200':
          description: 미션 목록 조회 성공
          schema:
            $ref: '#/definitions/StoreMissionsResponse'
        '400':
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/ParameterNotFoundError'
        '404':
          description: 가게 정보가 존재하지 않음
          schema:
            $ref: '#/definitions/StoreNotFoundError'
        '500':
          description: 서버 에러
          schema:
            $ref: '#/definitions/BaseError'

definitions:
  ParameterNotFoundError:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: false
      code:
        type: string
        example: 'VALID4001'
      message:
        type: string
        example: '전달한 파라미터 정보가 잘못되었습니다.'
  BaseError:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: false
      code:
        type: string
        example: 'COMMON000'
      message:
        type: string
        example: '서버 에러, 관리자에게 문의 바랍니다.'
  StoreNotFoundError:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: false
      code:
        type: string
        example: 'STORE4001'
      message:
        type: string
        example: '가게 정보가 존재하지 않습니다.'
  StoreReviewResponse:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: true
      code:
        type: integer
        example: 2010
      message:
        type: string
        example: "created!"
      result:
        type: object
        properties:
          name:
            type: string
            description: 가게 명
            example: '삼성동 한식집'
          rate:
            type: number
            format: float
            description: 가게 평점
            example: 4.5
  CreateStoreRequest:
    type: object
    properties:
      category:
        type: integer
        description: 가게 카테고리 id
        example: 1
      region:
        type: integer
        description: 지역 id
        example: 3
      name:
        type: string
        description: 가게 명
        example: swagger Test name
      address:
        type: string
        description: 가게 주소
        example: swagger Test address
      status:
        type: string
        description: 가게 상태 (영업중, 휴업, 영업 중지)
        example: 영업중
  CreateStoreResponse:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: true
      code:
        type: integer
        example: 2010
      message:
        type: string
        example: "가게 등록 성공!"
      result:
        type: object
        properties:
          name:
            type: string
            description: 가게 명
            example: '삼성동 한식집'
          region:
            type: string
            description: 지역
            example: '삼성동'
          category:
            type: string
            description: 카테고리
            example: '한식'
  AddReviewRequest:
    type: object
    properties:
      rate:
        type: integer
        description: 리뷰 평점
        example: 5
      content:
        type: string
        description: 리뷰 내용
        example: '리뷰 내용'
  AddStoreMissionRequest:
    type: object
    properties:
      title:
        type: string
        description: 미션 제목
        example: 미션 제목
      reward:
        type: integer
        description: 미션 보상
        example: 50
      end_date_year:
        type: integer
        description: 마감 날짜 년도
        example: 2024
      end_date_month:
        type: integer
        description: 마감 날짜 월
        example: 6
      end_date_day:
        type: integer
        description: 마감 날짜 일
        example: 19
  StoreMissionResponse:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: true
      code:
        type: integer
        example: 2000
      message:
        type: string
        example: "미션 추가 성공"
      result:
        type: object
        properties:
          name:
            type: string
            description: 가게 명
            example: '삼성동 한식집'
          missionList:
            type: array
            description: 가게 미션 목록
            items:
              type: string
            example: 
              - "미션 1"
              - "미션 2"
  StoreReviewsResponse:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: true
      code:
        type: integer
        example: 2000
      message:
        type: string
        example: "리뷰 목록 조회 성공"
      result:
        type: object
        properties:
          totalElements:
            type: integer
            example: 20
          reviews:
            type: array
            items:
              type: object
              properties:
                nickname:
                  type: string
                  example: "닉네임"
                create_date:
                  type: string
                  format: date
                  example: "2024-06-21"
                rate:
                  type: number
                  format: float
                  example: 4.5
                content:
                  type: string
                  example: "리뷰 내용"
  StoreMissionsResponse:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: true
      code:
        type: integer
        example: 2000
      message:
        type: string
        example: "미션 목록 조회 성공"
      result:
        type: object
        properties:
          totalElements:
            type: integer
            example: 20
          missions:
            type: array
            items:
              type: object
              properties:
                title:
                  type: string
                  example: "미션 제목"
                reward:
                  type: integer
                  example: 500
                end_date:
                  type: string
                  format: date
                  example: "2024-06-21"
