paths:
  /users/signin:
    post:
      tags:
        - User
      summary: 회원가입
      parameters:
        - name: signIn
          in: body
          required: true
          schema:
            $ref: '#/definitions/SignInRequest'
      responses:
        '201':
          description: 회원 가입 성공!
          schema:
            $ref: '#/definitions/SignInSuccessResponse'
        '400':
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/BaseError'
        '500':
          description: 서버 에러
          schema:
            $ref: '#/definitions/BaseError'

  /users/missions:
    post:
      tags:
        - User
      summary: 사용자 미션 추가
      description: 사용자가 도전 중인 미션에 새로운 미션을 추가합니다.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/AddUserMissionRequest'
      responses:
        '200':
          description: 미션 추가 성공
          schema:
            $ref: '#/definitions/AddUserMissionResponse'
        '400':
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/BaseError'
        '500':
          description: 서버 에러
          schema:
            $ref: '#/definitions/BaseError'

  /users/{user-id}/reviews:
    get:
      tags:
        - User
      summary: 내가 작성한 리뷰 목록 조회
      parameters:
        - name: user-id
          in: path
          required: true
          type: integer
          description: 유저 ID
        - name: page
          in: query
          required: false
          type: integer
          description: 요청 페이지 (1이상)
        - name: size
          in: query
          required: false
          type: integer
          description: 조회할 리뷰 개수
      responses:
        '200':
          description: 리뷰 목록 조회 성공
          schema:
            $ref: '#/definitions/UserReviewsResponse'
        '400':
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/ParameterNotFoundError'
        '404':
          description: 유저 정보가 존재하지 않음
          schema:
            $ref: '#/definitions/UsereNotFoundError'
        '500':
          description: 서버 에러
          schema:
            $ref: '#/definitions/BaseError'

  /users/{user-id}/missions/continue:
    get:
      tags:
        - User
      summary: 내가 진행중인 미션 목록 조회
      parameters:
        - name: user-id
          in: path
          required: true
          type: integer
          description: 유저 ID
        - name: page
          in: query
          required: false
          type: integer
          description: 요청 페이지 (1이상)
        - name: size
          in: query
          required: false
          type: integer
          description: 조회할 미션 개수
      responses:
        '200':
          description: 진행 중인 미션 목록 조회 성공
          schema:
            $ref: '#/definitions/UserContinueMissionsResponse'
        '400':
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/ParameterNotFoundError'
        '404':
          description: 유저 정보가 존재하지 않음
          schema:
            $ref: '#/definitions/UsereNotFoundError'
        '500':
          description: 서버 에러
          schema:
            $ref: '#/definitions/BaseError'

  /users/{user-id}/missions/{mission-id}:
    patch:
      tags:
        - User
      summary: 진행중인 미션 진행 완료로 바꾸기
      parameters:
        - name: user-id
          in: path
          required: true
          type: integer
          description: 유저 ID
        - name: mission-id
          in: path
          required: true
          type: integer
          description: 미션 ID
      responses:
        '200':
          description: 진행중인 미션 진행 완료로 바꾸기 성공
          schema:
            $ref: '#/definitions/DefaultSuccessResponse'
        '400':
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/ParameterNotFoundError'
        '404':
          description: 유저 정보가 존재하지 않음
          schema:
            $ref: '#/definitions/UsereNotFoundError'
        '401':
          description: 미션 정보가 존재하지 않음
          schema:
            $ref: '#/definitions/MissionNotFoundError'
        '402':
          description: 이미 완료한 미션
          schema:
            $ref: '#/definitions/MissionAlreadyFinishedError'
        '500':
          description: 서버 에러
          schema:
            $ref: '#/definitions/BaseError'

definitions:
  SignInRequest:
    type: object
    properties:
      name:
        type: string
        description: 유저 이름
        example: swagger
      gender:
        type: string
        description: 유저 성별
        example: M
      birthYear:
        type: integer
        description: 생일 년도
        example: 2000
      birthMonth:
        type: integer
        description: 생일 월
        example: 1
      birthDay:
        type: integer
        description: 생일 일
        example: 31
      addr:
        type: string
        description: 주소
        example: swagger Test address
      phone:
        type: string
        description: 전화 번호
        example: 010-0000-0000
      prefer:
        type: array
        description: 선호 카테고리 번호
        example: [1, 3, 5]

  SignInSuccessResponse:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: true
      code:
        type: integer
        example: 2010
      message:
        type: string
        example: "created!"
      result:
        type: object
        properties:
          email:
            type: string
            example: swaggerTest@mail.com
          name:
            type: string
            example: swagger
          preferCategory:
            type: array
            items:
              type: string
            example: 
              - 한식
              - 일식

  AddUserMissionRequest:
    type: object
    properties:
      mission_id:
        type: integer
        description: 추가할 미션의 ID
        example: 3

  AddUserMissionResponse:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: true
      code:
        type: integer
        example: 2000
      message:
        type: string
        example: "success!"
      result:
        type: object
        properties:
          name:
            type: string
            description: 사용자 이름
            example: swagger
          missionList:
            type: array
            description: 사용자가 도전 중인 미션 목록
            items:
              type: string
            example: 
              - "미션 1"
              - "미션 2"
              - "미션 3"

  UserReviewsResponse:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: true
      code:
        type: integer
        example: 2000
      message:
        type: string
        example: "success!"
      result:
        type: object
        properties:
          totalElements:
            type: integer
            example: 20
          reviews:
            type: array
            items:
              type: object
              properties:
                nickname:
                  type: string
                  example: "닉네임"
                create_date:
                  type: string
                  format: date
                  example: "2024-06-21"
                rate:
                  type: number
                  format: float
                  example: 4.5
                content:
                  type: string
                  example: "리뷰 내용"

  UserContinueMissionsResponse:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: true
      code:
        type: integer
        example: 2000
      message:
        type: string
        example: "success!"
      result:
        type: object
        properties:
          totalElements:
            type: integer
            example: 20
          missions:
            type: array
            items:
              type: object
              properties:
                restaurant_name:
                  type: string
                  example: "가게 이름"
                title:
                  type: string
                  example: "미션 제목"
                reward:
                  type: integer
                  example: 500
                end_date:
                  type: string
                  format: date
                  example: "2024.06.21"

  DefaultSuccessResponse:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: true
      code:
        type: integer
        example: 2000
      message:
        type: string
        example: "success!"

  ParameterNotFoundError:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: false
      code:
        type: string
        example: 'VALID4001'
      message:
        type: string
        example: '전달한 파라미터 정보가 잘못되었습니다.'

  BaseError:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: false
      code:
        type: string
        example: 'COMMON000'
      message:
        type: string
        example: '서버 에러, 관리자에게 문의 바랍니다.'

  UsereNotFoundError:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: false
      code:
        type: string
        example: 'MEMBER4001'
      message:
        type: string
        example: '사용자가 없습니다.'
  MissionNotFoundError:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: false
      code:
        type: string
        example: 'MISSION4002'
      message:
        type: string
        example: '진행중인 미션이 아닙니다.'
  MissionAlreadyFinishedError:
    type: object
    properties:
      isSuccess:
        type: boolean
        example: false
      code:
        type: string
        example: 'MISSION4003'
      message:
        type: string
        example: '이미 완료한 미션입니다.'
